{u'contributors': None,
 u'coordinates': None,
 u'created_at': u'Thu Feb 26 09:43:43 +0000 2015',
 u'entities': {u'hashtags': [{u'indices': [0, 19],
    u'text': u'CorporateEspionage'}],
  u'symbols': [],
  u'urls': [],
  u'user_mentions': []},
 u'favorite_count': 7,
 u'favorited': False,
 u'geo': None,
 u'id': 570881888715288576,
 u'id_str': u'570881888715288576',
 u'in_reply_to_screen_name': None,
 u'in_reply_to_status_id': None,
 u'in_reply_to_status_id_str': None,
 u'in_reply_to_user_id': None,
 u'in_reply_to_user_id_str': None,
 u'lang': u'en',
 u'place': None,
 u'retweet_count': 9,
 u'retweeted': False,
 u'source': u'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
 u'text': u'#CorporateEspionage case: Delhi court remands accused Jitender Nagpal and Vipan Kumar to five days police custody. (PTI)',
 u'truncated': False,
 u'user': {u'contributors_enabled': False,
  u'created_at': u'Mon Apr 19 10:50:15 +0000 2010',
  u'default_profile': False,
  u'default_profile_image': False,
  u'description': u'News. Views. Analysis. Conversations. \n\nIndia\u2019s No.1 digital news destination, world\u2019s largest-selling English newspaper.',
  u'entities': {u'description': {u'urls': []},
   u'url': {u'urls': [{u'display_url': u'timesofindia.com',
      u'expanded_url': u'http://www.timesofindia.com',
      u'indices': [0, 22],
      u'url': u'http://t.co/QQBl4zp3J2'}]}},
  u'favourites_count': 178,
  u'follow_request_sent': None,
  u'followers_count': 4011687,
  u'following': None,
  u'friends_count': 469,
  u'geo_enabled': False,
  u'id': 134758540,
  u'id_str': u'134758540',
  u'is_translation_enabled': False,
  u'is_translator': False,
  u'lang': u'en',
  u'listed_count': 7814,
  u'location': u'New Delhi',
  u'name': u'Times of India',
  u'notifications': None,
  u'profile_background_color': u'C0DEED',
  u'profile_background_image_url': u'http://pbs.twimg.com/profile_background_images/94861244/toi_twitter2b.jpg',
  u'profile_background_image_url_https': u'https://pbs.twimg.com/profile_background_images/94861244/toi_twitter2b.jpg',
  u'profile_background_tile': False,
  u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/134758540/1426572568',
  u'profile_image_url': u'http://pbs.twimg.com/profile_images/501345800736092162/D3PvZhP0_normal.jpeg',
  u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/501345800736092162/D3PvZhP0_normal.jpeg',
  u'profile_link_color': u'0084B4',
  u'profile_location': None,
  u'profile_sidebar_border_color': u'C0DEED',
  u'profile_sidebar_fill_color': u'DDEEF6',
  u'profile_text_color': u'333333',
  u'profile_use_background_image': True,
  u'protected': False,
  u'screen_name': u'timesofindia',
  u'statuses_count': 173269,
  u'time_zone': u'New Delhi',
  u'url': u'http://t.co/QQBl4zp3J2',
  u'utc_offset': 19800,
  u'verified': True}}