{u'contributors': None,
 u'coordinates': None,
 u'created_at': u'Fri Feb 27 01:36:16 +0000 2015',
 u'entities': {u'hashtags': [{u'indices': [17, 36],
    u'text': u'CorporateEspionage'}],
  u'symbols': [],
  u'urls': [{u'display_url': u'timesofindia.indiatimes.com/corporate-espi\u2026',
    u'expanded_url': u'http://timesofindia.indiatimes.com/corporate-espionage-in-ministries/top-stories/Corporate-espionage-probe-Cops-question-RIL-president/articleshow/46389121.cms',
    u'indices': [74, 96],
    u'url': u'http://t.co/m5T2tChzDF'},
   {u'display_url': u'timesofindia.indiatimes.com/Corporate-espi\u2026',
    u'expanded_url': u'http://timesofindia.indiatimes.com/Corporate-espionage-in-ministries/specialcoverage/46328027.cms',
    u'indices': [121, 140],
    u'url': u'http://t.co/6RX3i0KdRI'}],
  u'user_mentions': [{u'id': 251131108,
    u'id_str': u'251131108',
    u'indices': [3, 15],
    u'name': u'Ratan Maitra',
    u'screen_name': u'ratanmaitra'}]},
 u'favorite_count': 0,
 u'favorited': False,
 u'geo': None,
 u'id': 571121605331406848,
 u'id_str': u'571121605331406848',
 u'in_reply_to_screen_name': None,
 u'in_reply_to_status_id': None,
 u'in_reply_to_status_id_str': None,
 u'in_reply_to_user_id': None,
 u'in_reply_to_user_id_str': None,
 u'lang': u'en',
 u'place': None,
 u'possibly_sensitive': False,
 u'possibly_sensitive_appealable': False,
 u'retweet_count': 14,
 u'retweeted': False,
 u'retweeted_status': {u'contributors': None,
  u'coordinates': None,
  u'created_at': u'Fri Feb 27 00:50:50 +0000 2015',
  u'entities': {u'hashtags': [{u'indices': [0, 19],
     u'text': u'CorporateEspionage'}],
   u'symbols': [],
   u'urls': [{u'display_url': u'timesofindia.indiatimes.com/corporate-espi\u2026',
     u'expanded_url': u'http://timesofindia.indiatimes.com/corporate-espionage-in-ministries/top-stories/Corporate-espionage-probe-Cops-question-RIL-president/articleshow/46389121.cms',
     u'indices': [57, 79],
     u'url': u'http://t.co/m5T2tChzDF'},
    {u'display_url': u'timesofindia.indiatimes.com/Corporate-espi\u2026',
     u'expanded_url': u'http://timesofindia.indiatimes.com/Corporate-espionage-in-ministries/specialcoverage/46328027.cms',
     u'indices': [104, 126],
     u'url': u'http://t.co/6RX3i0KdRI'}],
   u'user_mentions': []},
  u'favorite_count': 4,
  u'favorited': False,
  u'geo': None,
  u'id': 571110170484346880,
  u'id_str': u'571110170484346880',
  u'in_reply_to_screen_name': None,
  u'in_reply_to_status_id': None,
  u'in_reply_to_status_id_str': None,
  u'in_reply_to_user_id': None,
  u'in_reply_to_user_id_str': None,
  u'lang': u'en',
  u'place': None,
  u'possibly_sensitive': False,
  u'possibly_sensitive_appealable': False,
  u'retweet_count': 14,
  u'retweeted': False,
  u'source': u'<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  u'text': u'#CorporateEspionage probe: Cops question RIL president \n\nhttp://t.co/m5T2tChzDF \n\nMore "Stories" Here : http://t.co/6RX3i0KdRI',
  u'truncated': False,
  u'user': {u'contributors_enabled': False,
   u'created_at': u'Sat Feb 12 14:12:49 +0000 2011',
   u'default_profile': False,
   u'default_profile_image': False,
   u'description': u'Collation & Interpretation of News on Anti-Corruption #AAP Movement, For Your Attention & Action to Change The System --- (\u0935\u094d\u092f\u0935\u0938\u094d\u0925\u093e \u092a\u0930\u093f\u0935\u0930\u094d\u0924\u0928, \u0928 \u0915\u0947\u0935\u0932 \u0938\u0924\u094d\u0924\u093e)',
   u'entities': {u'description': {u'urls': []}},
   u'favourites_count': 11,
   u'follow_request_sent': None,
   u'followers_count': 3210,
   u'following': None,
   u'friends_count': 7,
   u'geo_enabled': False,
   u'id': 251131108,
   u'id_str': u'251131108',
   u'is_translation_enabled': True,
   u'is_translator': False,
   u'lang': u'en',
   u'listed_count': 10,
   u'location': u'\u092c\u0940\u0928\u093e \u0915\u0930\u092a\u094d\u0936\u0928, \u092d\u093e\u0930\u0924 \u092e\u0939\u093e\u0928 !!!',
   u'name': u'Ratan Maitra',
   u'notifications': None,
   u'profile_background_color': u'1A1B1F',
   u'profile_background_image_url': u'http://pbs.twimg.com/profile_background_images/589592245/pv4il6n1whk5viiwrzaw.jpeg',
   u'profile_background_image_url_https': u'https://pbs.twimg.com/profile_background_images/589592245/pv4il6n1whk5viiwrzaw.jpeg',
   u'profile_background_tile': False,
   u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/251131108/1353161669',
   u'profile_image_url': u'http://pbs.twimg.com/profile_images/2578869315/oeieaauvxzdm1iw2co7y_normal.jpeg',
   u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/2578869315/oeieaauvxzdm1iw2co7y_normal.jpeg',
   u'profile_link_color': u'ABB8C2',
   u'profile_location': None,
   u'profile_sidebar_border_color': u'181A1E',
   u'profile_sidebar_fill_color': u'252429',
   u'profile_text_color': u'666666',
   u'profile_use_background_image': True,
   u'protected': False,
   u'screen_name': u'ratanmaitra',
   u'statuses_count': 79445,
   u'time_zone': u'Kolkata',
   u'url': None,
   u'utc_offset': 19800,
   u'verified': False}},
 u'source': u'<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 u'text': u'RT @ratanmaitra: #CorporateEspionage probe: Cops question RIL president \n\nhttp://t.co/m5T2tChzDF \n\nMore "Stories" Here : http://t.co/6RX3i0\u2026',
 u'truncated': False,
 u'user': {u'contributors_enabled': False,
  u'created_at': u'Mon Oct 05 06:51:43 +0000 2009',
  u'default_profile': False,
  u'default_profile_image': False,
  u'description': u'Supporter of AAP n AK. Lawyer. RTs not endorsements. Tweets are personal. Bhakts/Abusers please stay away.',
  u'entities': {u'description': {u'urls': []}},
  u'favourites_count': 41082,
  u'follow_request_sent': None,
  u'followers_count': 2842,
  u'following': None,
  u'friends_count': 1648,
  u'geo_enabled': True,
  u'id': 79947136,
  u'id_str': u'79947136',
  u'is_translation_enabled': False,
  u'is_translator': False,
  u'lang': u'en',
  u'listed_count': 54,
  u'location': u'',
  u'name': u'#AAPistheHope',
  u'notifications': None,
  u'profile_background_color': u'CCCCCC',
  u'profile_background_image_url': u'http://pbs.twimg.com/profile_background_images/612938183/5q7biuzomedme3kh48x1.jpeg',
  u'profile_background_image_url_https': u'https://pbs.twimg.com/profile_background_images/612938183/5q7biuzomedme3kh48x1.jpeg',
  u'profile_background_tile': False,
  u'profile_banner_url': u'https://pbs.twimg.com/profile_banners/79947136/1418043582',
  u'profile_image_url': u'http://pbs.twimg.com/profile_images/564108058603683840/UWFnqaVd_normal.jpeg',
  u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/564108058603683840/UWFnqaVd_normal.jpeg',
  u'profile_link_color': u'666666',
  u'profile_location': None,
  u'profile_sidebar_border_color': u'000000',
  u'profile_sidebar_fill_color': u'333333',
  u'profile_text_color': u'999999',
  u'profile_use_background_image': True,
  u'protected': False,
  u'screen_name': u'AAPlogical',
  u'statuses_count': 131900,
  u'time_zone': u'New Delhi',
  u'url': None,
  u'utc_offset': 19800,
  u'verified': False}}